#! /bin/sh

i=1
for monitor in $(bspc query -M); do
  bspc monitor $monitor \
    -n "$i" \
    -d $i/{i,ii,iii,iv}
  let i++
done
NMOD=$i
unset i

bspc config top_padding 14

# Visaul options

bspc config split_ratio        0.50
bspc config border_width       1
bspc config window_gap         4
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Rules
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
