#!/bin/sh

while read -r line; do
  case $line in
    date)
      notify-send -t 5 -u normal "Date" "`date`"
      ;;
    wifi)
      notify-send -t 5 -u normal "WiFi" "You have a penis"
  esac
  done

