#!/bin/bash

# WIFI ICONS
# 
INTERFACE=wlp1s0

QUAL=`iwconfig $INTERFACE | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
MAX=`iwconfig $INTERFACE | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
SSID=`iwconfig wlp1s0 | grep 'ESSID:' | awk -F\" '{print $ (NF-1)}'`

PERC=`echo $QUAL*100/$MAX | bc`

icon=""
case $PERC in
	[0-4])
		icon=""
	;;
	[4-9])
		icon=""
	;;
	[2-3]*)
		icon=""
	;;
	[4-5]*)
		icon=""
	;;
	[6-7]*)
		icon=""
	;;
	*)
		icon=""
	;;
esac

echo "$icon $SSID"
