#! /bin/sh

panel_fifo=/tmp/panel.fifo
panel_height=16
font_family='-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1,-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1'
color_fg='#ff4e595f'
color_bg='#ff242b33'
paneldir=$HOME/.config/bspwm/panel

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$panel_fifo" ] && rm "$panel_fifo"
mkfifo "$panel_fifo"

bspc control --subscribe > "$panel_fifo" &
xtitle -sf 'T%s' > "$panel_fifo" &
#clock -sf 'S%a %H:%M' > "$panel_fifo" &
conky -c $paneldir/panel_conky > "$panel_fifo" &

cat "$panel_fifo" | $paneldir/parse.rb | bar -g x$panel_height -f "$font_family" -F "$color_fg" -B "$color_bg" &
wait
